---
# This role will install MySQL and create db user and give permissions.

- name: Install Mysql package
  yum: name={{ item }} state=present
  with_items:
   - mysql
   - mysql-server
   - MySQL-python27
   
- name: Move MyQSL data dir
  command: mv /var/lib/mysql /data/ removes=/var/lib/mysql creates=/data/mysql

- name: Copy MySQL configuration file
  copy: src=my.cnf dest=/etc/my.cnf
  notify: restart mysqld

- name: wait for db server to come up
  wait_for: host=127.0.0.1 port=3306 state=started timeout=80

- name: ensure MySQL is running (and enable it at boot)
  service: name=mysqld state=started enabled=yes

- name: stat /root/.my.cnf
  stat: path=/root/.my.cnf
  register: root_my_cnf

- include: set_mysql_pwd.yml
  when: not root_my_cnf.stat.exists

- name: Create Application Database
  mysql_db: name={{ db_name }} state=present
  register: db_exist

- name: Generate DB User password
  shell: dd if=/dev/urandom bs=1 count=10 2>/dev/null | base64 | cut -c -14
  no_log: True
  register: my_usr_pwd
  when: db_exist.changed

- name: Create Application DB User
  mysql_user: name={{ db_user }} password={{ my_usr_pwd.stdout }} priv={{ db_name }}.*:ALL host='%' state=present
  when: db_exist.changed

- name: MySQL details
  # http://docs.ansible.com/YAMLSyntax.html#gotchas
  debug: msg="MySQL connection details DB name={{db_name}} DB user={{db_user}} DB pass={{my_usr_pwd.stdout}}"
  when: db_exist.changed
  
- name: Create /data/bin
  file: path=/data/bin state=directory mode=0700