---

- name: Generate Mysql root password
  shell: dd if=/dev/urandom bs=1 count=10 2>/dev/null | base64 | cut -c -14
  no_log: True
  register: my_pwd

- name: PWD
  debug: msg="MySQL root password  =====================> {{my_pwd.stdout}} <====================="

- name: Set root password
  mysql_user: name=root password={{my_pwd.stdout}} host="{{ item }}"
  with_items:
  - 127.0.0.1
  - ::1
  - localhost 

- name: Set up /root/.my.cnf
  template: src=root_my.cnf.j2 dest=/root/.my.cnf owner=root mode=600
