---
  - name: install some base pkg
    yum: name={{item}} state=present
    with_items:
     - mysql
     - php-fpm
     - php-mysql
     - php-gd
     - php-pdo
     - php-xml
     - php-curl
     - php-pecl-apc
     - php-drush-drush
     - php-mbstring

