---
# This role contains common plays that will run on all nodes.

- name: Install python bindings for SE Linux
  yum: name={{ item }} state=present
  with_items:
   - libselinux-python
   - libsemanage-python

- name: Upgrade all packages
  yum: name=* state=latest

- name: Create the repository for EPEL
  copy: src=epel.repo dest=/etc/yum.repos.d/epel.repo

- name: Create the GPG key for EPEL
  copy: src=RPM-GPG-KEY-EPEL-6 dest=/etc/pki/rpm-gpg

- name: install some base pkg
  yum: name={{item}} state=present
  with_items:
   - vim
   - openssh-clients
   - wget
   - curl

- name: disable and stop iptables service
  service: name=iptables enabled=no state=stopped
